config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  get '/books/:id/comments', to: 'books#comments', as: 'comments'
  post '/books/add_comment', to: 'books#add_comment', as: 'add_comment'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  has_many :description_books
end

app/models/description_book.rb
class DescriptionBook < TestBase
  belongs_to :book
end

app/models/test_base.rb
class TestBase < ActiveRecord::Base
  establish_connection DB_CACHE
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_id, only: [:show, :edit, :update, :comments, :add_comment]

  @comment = DescriptionBook
  def index
    @book = Book.all.includes(:description_books)
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def comments
  #   @comment = DescriptionBook.where("book_id = ?" )
  #   agregar una migraciòn con el campo DescriptionBook, relacion!!
  end

  def add_comment
    if DescriptionBook.new(description_params).save
      redirect_to @book
    else
      render :comments
    end
  end

  def set_id
    @book = Book.find(params[:id])
  end

  private
  def book_params
    params.require(:book).permit(:title, :author)
    #no me deja mostrar en pantalla los libros si no tienen comentarios
  end
  private
  def description_params
    params.require(:description_book).permit(:comments, :book_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/comments.html.erb
<h1>Agregar Comentarios</h1>
<%= form_for :description_book, url: add_comment_path do |f| %>
  <div>
    <%= f.label :comments %>
    <%= f.text_field :comments, class: "form-control" %>
  </div>
  <%= f.hidden_field :book_id, value: @book.id %>
  <%= hidden_field_tag :id, @book.id %>
  <br>
  <div>
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editar Libro</h1>
<%= form_for @book do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div>
    <%= f.label :author %>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <br>
  <div>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/books/index.html.erb
<h1>Libros</h1>
<%= link_to "Nuevo Libro", new_book_path %>
<table class="table">
  <thead>
    <tr>
      <th>Título</th>
      <th>Descripción</th>
      <th>Comentarios</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
    <% @book.each do |book| %>
      <%# book.description_books.each do |comentario| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td>
            <% book.description_books.each do |comentario| %>
              <%= comentario.comments + " | " %>
            <% end %>
          </td>
          <td>
            <% if signed_in? %>
            <%= link_to "Editar", edit_book_path(book) %>
            <%= link_to "Comentrar", comments_path(book) %>
            <% else %>
            <%= link_to "Mostrar", book, class: "btn btn-primary" %>
            <% end %>
            <%#= link_to "Eliminar", book, method: :delete, data: { confirm: "¿Estás seguro de eliminar este libro?" } %>
          </td>
        </tr>
      <%# end %>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
  <h1>Nuevo Libro</h1>
  <%= form_for @book do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div>
      <%= f.label :author %>
      <%= f.text_field :author, class: "form-control" %>
    </div>
    <br>
    <div>
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/books/show.html.erb
<h1>Detalles del Libro</h1>
<div>
  Nombre: <%= @book.title %>
</div>
<div>
  Autor: <%= @book.author %>
</div>
<div>
  Comentario:
  <% @book.description_books.each do |comentario| %>
    <%= comentario.comments + ","%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaBD</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> -->
  </head>

  <body>
    <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
      <div class="container">
        <%= link_to "Books", books_path, class: "navbar-brand" %>


        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav ml-auto">
            <% if signed_in? %>
              <li class="nav-item"><%= link_to "Salir", destroy_user_session_path, class: "nav-link", method: :delete %></li>
            <% else %>
              <li class="nav-item"><%= link_to "Registrarse", new_user_registration_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Ingresar", new_user_session_path, class: "nav-link" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <br>
      <%= yield %>
    </div>

  </body>
</html>